version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    # conflicting/cover same issues
    - forcetypeassert # coverd by errcheck

    # personal preference
    - gocritic
    - depguard
    - funlen
    - exhaustruct
    - gochecknoglobals
    - err113
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wsl
    # premature optimisation that creates inconsistent code (sometimes Sprintf, sometimes string concatenation)
    # consider enabling _if_ you've profile performance _and_ Sprintf calls are slowing you down
    - perfsprint
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: false
    nolintlint:
      require-specific: true
    revive:
      rules:
        - name: exported
          disabled: true
        - name: context-as-argument
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
