name: Checks
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go_version:
          - "stable"
          - "oldstable"
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5
        with:
          go-version: ${{ matrix.go_version }}
      - name: test
        run: make report-coverage
      - name: check-coverage
        # only bother checking coverage on Linux
        if: matrix.os == 'ubuntu-latest'
        run: make check-coverage

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
    - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55  # v5
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5
      with:
        go-version-file: 'go.mod'
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
